CREATE TABLE [dbo].[AppUser]
(
	[Id]			BIGINT IDENTITY(1,1) NOT NULL,
	[Name]			VARCHAR(100) NOT NULL,
	[Email]			VARCHAR(100) NOT NULL,
	[Password]		VARCHAR(100) NOT NULL,
	[CreatedDate]	DATETIME NOT NULL CONSTRAINT DF_AppUser_CreatedDate DEFAULT(GETUTCDATE())

	CONSTRAINT [PK__AppUser] PRIMARY KEY CLUSTERED
	(
		[Id] ASC
	)
)
