name: Build and deploy Web API

env:
  AZURE_WEBAPP_NAME: 'daisuke'          # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0'                         # set this to the .NET Core version to use
  API_DIRECTORY: './Job/Code/Job.Services'      # points to the correct directory
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build and Deploy Web Api
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.API_DIRECTORY }}

      - name: Build
        run: dotnet build ${{ env.API_DIRECTORY }} --no-restore -c Release

      - name: Publish
        run: dotnet publish ${{ env.API_DIRECTORY }} --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


        
